[tool.poetry]
name = "nestipy-cli"
version = "0.2.1"
description = "Nestipy is a Python framework built on top of FastAPI that follows the modular architecture of NestJS"
authors = ["tsiresymila <tsiresymila@gmail.com>"]
readme = "README.md"
packages = [{include = "nestipy_cli", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
minijinja = "^1.0.16"
click-aliases = "^1.0.4"
questionary = "^2.0.1"
aiofile = "^3.8.8"
autoflake = "^2.3.1"
isort = "^5.13.2"
autopep8 = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nestipy = "nestipy_cli.cli:main"
