"""Generate an Inertia.js frontend (React / Vue / Svelte) at scaffold time.

Unlike the backend (copied from a template), the frontend is generated by running
the real framework tooling (`npm create vite`) and then wiring Inertia on top, so
the generated app always tracks the latest framework + Inertia versions.
"""

import os
import shutil
import subprocess

FRAMEWORKS = ("react", "vue", "svelte")

# create-vite template + matching Inertia adapter + entry filename per framework
_VITE_TEMPLATE = {"react": "react-ts", "vue": "vue-ts", "svelte": "svelte-ts"}
_INERTIA_PKG = {
    "react": "@inertiajs/react",
    "vue": "@inertiajs/vue3",
    "svelte": "@inertiajs/svelte",
}
_ENTRY = {"react": "src/main.tsx", "vue": "src/main.ts", "svelte": "src/main.ts"}
_PAGE_EXT = {"react": "tsx", "vue": "vue", "svelte": "svelte"}

_NESTIPY_PLUGIN = """import type { PluginOption } from "vite";

type Input = {
    entry: string;
    ssr?: string;
    manifest?: string;
};
type NestipyPlugin = (options: Input) => PluginOption;

const nestipyVite: NestipyPlugin = ({ entry, ssr, manifest = "manifest.json" }) => {
    return {
        name: "nestipy-vite-plugin",
        config: (config, env) => {
            return {
                ...config,
                build: {
                    manifest: env.isSsrBuild ? false : manifest,
                    outDir: env.isSsrBuild ? "dist/ssr" : "dist",
                    rollupOptions: {
                        input: env.isSsrBuild && ssr ? ssr : entry,
                    },
                },
            };
        },
    };
};

export default nestipyVite;
"""

_VITE_CONFIG = {
    "react": """import {{ defineConfig }} from 'vite'
import react from '@vitejs/plugin-react'
import nestipyVite from './nestipy.inertia'

export default defineConfig({{
    plugins: [react(), nestipyVite({{ entry: '{entry}' }})],
}})
""",
    "vue": """import {{ defineConfig }} from 'vite'
import vue from '@vitejs/plugin-vue'
import nestipyVite from './nestipy.inertia'

export default defineConfig({{
    plugins: [vue(), nestipyVite({{ entry: '{entry}' }})],
}})
""",
    "svelte": """import {{ defineConfig }} from 'vite'
import {{ svelte }} from '@sveltejs/vite-plugin-svelte'
import nestipyVite from './nestipy.inertia'

export default defineConfig({{
    plugins: [svelte(), nestipyVite({{ entry: '{entry}' }})],
}})
""",
}

_ENTRY_CONTENT = {
    "react": """import { createInertiaApp } from '@inertiajs/react'
import { createRoot } from 'react-dom/client'

createInertiaApp({
    resolve: (name) => {
        const pages = import.meta.glob('./Pages/**/*.tsx', { eager: true })
        return pages[`./Pages/${name}.tsx`] as never
    },
    setup({ el, App, props }) {
        createRoot(el).render(<App {...props} />)
    },
})
""",
    "vue": """import { createApp, h, type DefineComponent } from 'vue'
import { createInertiaApp } from '@inertiajs/vue3'

createInertiaApp({
    resolve: (name) => {
        const pages = import.meta.glob<DefineComponent>('./Pages/**/*.vue', {
            eager: true,
        })
        return pages[`./Pages/${name}.vue`]
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .mount(el)
    },
})
""",
    "svelte": """import { createInertiaApp } from '@inertiajs/svelte'
import { mount } from 'svelte'

createInertiaApp({
    resolve: (name) => {
        const pages = import.meta.glob('./Pages/**/*.svelte', { eager: true })
        return pages[`./Pages/${name}.svelte`] as never
    },
    setup({ el, App, props }) {
        mount(App as never, { target: el as never, props })
    },
})
""",
}

_INDEX_PAGE = {
    "react": """import { Link } from '@inertiajs/react'

type Props = {
    message: string
    details?: string
    stats?: { users: number; online: number }
}

export default function Index({ message, details, stats }: Props) {
    return (
        <main>
            <h1>{message}</h1>
            <nav style={{ display: 'flex', gap: '1rem' }}>
                <Link href="/about">About</Link>
                <Link href="/" only={['details']}>
                    Partial reload (load details)
                </Link>
            </nav>
            <p>Optional prop: {details ?? '— (not loaded yet)'}</p>
            <p>Deferred stats: {stats ? JSON.stringify(stats) : 'loading…'}</p>
        </main>
    )
}
""",
    "vue": """<script setup lang="ts">
import { Link } from '@inertiajs/vue3'

defineProps<{
    message: string
    details?: string
    stats?: { users: number; online: number }
}>()
</script>

<template>
    <main>
        <h1>{{ message }}</h1>
        <nav style="display: flex; gap: 1rem">
            <Link href="/about">About</Link>
            <Link href="/" :only="['details']">Partial reload (load details)</Link>
        </nav>
        <p>Optional prop: {{ details ?? '— (not loaded yet)' }}</p>
        <p>Deferred stats: {{ stats ? JSON.stringify(stats) : 'loading…' }}</p>
    </main>
</template>
""",
    "svelte": """<script lang="ts">
    import { inertia } from '@inertiajs/svelte'

    let { message, details, stats } = $props()
</script>

<main>
    <h1>{message}</h1>
    <nav style="display: flex; gap: 1rem">
        <a href="/about" use:inertia>About</a>
        <a href="/" use:inertia={{ only: ['details'] }}>Partial reload (load details)</a>
    </nav>
    <p>Optional prop: {details ?? '— (not loaded yet)'}</p>
    <p>Deferred stats: {stats ? JSON.stringify(stats) : 'loading…'}</p>
</main>
""",
}

# The Inertia root template lives in the BACKEND (views/index.html). React needs the
# Vite React-refresh preamble (viteReactRefresh) in dev or @vitejs/plugin-react throws;
# Vue/Svelte must NOT include it. So it is written per chosen framework.
def _views_index(framework: str) -> str:
    refresh = "{{ viteReactRefresh() }}\n" if framework == "react" else ""
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '    <meta charset="UTF-8" />\n'
        '    <link rel="icon" type="image/svg+xml" href="/vite.svg" />\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        "    <title>Nestipy + Inertia.js</title>\n"
        "    {{ inertiaHead() }}\n"
        "</head>\n"
        "<body>\n"
        f"{refresh}"
        "{{ inertiaBody() }}\n"
        "</body>\n"
        "</html>\n"
    )


_ABOUT_PAGE = {
    "react": """import { Link } from '@inertiajs/react'

export default function About({ framework }: { framework: string }) {
    return (
        <main>
            <h1>About</h1>
            <p>Built with {framework}.</p>
            <Link href="/">← Back home</Link>
        </main>
    )
}
""",
    "vue": """<script setup lang="ts">
import { Link } from '@inertiajs/vue3'

defineProps<{ framework: string }>()
</script>

<template>
    <main>
        <h1>About</h1>
        <p>Built with {{ framework }}.</p>
        <Link href="/">← Back home</Link>
    </main>
</template>
""",
    "svelte": """<script lang="ts">
    import { inertia } from '@inertiajs/svelte'

    let { framework } = $props()
</script>

<main>
    <h1>About</h1>
    <p>Built with {framework}.</p>
    <a href="/" use:inertia>← Back home</a>
</main>
""",
}


def npm_available() -> bool:
    return shutil.which("npm") is not None


def _run(cmd: list[str], cwd: str) -> None:
    subprocess.run(cmd, cwd=cwd, check=True)


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


def _patch_backend_entrypoint(destination: str, entry_file: str) -> None:
    """Set `entrypoint_filename` on the backend's InertiaConfig to match the entry."""
    app_module = os.path.join(destination, "src", "app_module.py")
    if not os.path.exists(app_module):
        return
    with open(app_module, encoding="utf-8") as handle:
        text = handle.read()
    if "entrypoint_filename" in text or "InertiaConfig(" not in text:
        return
    text = text.replace(
        "InertiaConfig(",
        f'InertiaConfig(entrypoint_filename="{entry_file}", ',
        1,
    )
    with open(app_module, "w", encoding="utf-8") as handle:
        handle.write(text)


def scaffold_inertia_frontend(
    destination: str,
    framework: str,
    dir_name: str = "inertia",
    install: bool = True,
) -> None:
    """Create a Vite app for `framework` inside `<destination>/<dir_name>` and wire Inertia.

    Raises CalledProcessError / FileNotFoundError on tooling failure so the caller can
    report manual fallback steps.
    """
    fw = framework.lower()
    if fw not in FRAMEWORKS:
        raise ValueError(f"Unsupported framework: {framework}")

    template = _VITE_TEMPLATE[fw]
    frontend_path = os.path.join(destination, dir_name)
    entry = _ENTRY[fw]
    ext = _PAGE_EXT[fw]

    # 1. scaffold the base Vite app (non-interactive)
    _run(
        ["npm", "create", "vite@latest", dir_name, "--", "--template", template],
        cwd=destination,
    )

    # 2. drop the default boilerplate entry/app so Inertia owns the mount
    for stale in ("src/App.tsx", "src/App.vue", "src/App.svelte", "src/app.css"):
        stale_path = os.path.join(frontend_path, stale)
        if os.path.exists(stale_path):
            os.remove(stale_path)

    # 3. write the Nestipy Vite plugin, Inertia entry, vite config and pages
    _write(os.path.join(frontend_path, "nestipy.inertia.ts"), _NESTIPY_PLUGIN)
    _write(os.path.join(frontend_path, entry), _ENTRY_CONTENT[fw])
    _write(
        os.path.join(frontend_path, "vite.config.ts"),
        _VITE_CONFIG[fw].format(entry=f"./{entry}"),
    )
    _write(os.path.join(frontend_path, "src", "Pages", f"Index.{ext}"), _INDEX_PAGE[fw])
    _write(os.path.join(frontend_path, "src", "Pages", f"About.{ext}"), _ABOUT_PAGE[fw])

    # 4. write the backend Inertia root template matching the chosen framework
    _write(os.path.join(destination, "views", "index.html"), _views_index(fw))

    # 5. point the backend InertiaConfig at the right client entry. The adapter loads
    #    `{dev_url}/src/{entrypoint_filename}` in dev and the matching manifest key in
    #    prod; the default is main.tsx, so Vue/Svelte (main.ts) must override it.
    _patch_backend_entrypoint(destination, os.path.basename(entry))

    # 6. install deps + the Inertia adapter for this framework
    if install:
        _run(["npm", "install"], cwd=frontend_path)
        _run(["npm", "install", _INERTIA_PKG[fw]], cwd=frontend_path)
